-- DogWalk Social Phase 2 schema

create table if not exists public.walks (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  distance_m numeric not null default 0,
  elapsed_seconds integer not null default 0,
  point_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.warnings (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  message text not null,
  source text,
  created_at timestamptz not null default now()
);

create table if not exists public.follows (
  follower_id uuid not null references auth.users(id) on delete cascade,
  followee_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, followee_id),
  check (follower_id <> followee_id)
);

alter table public.walks enable row level security;
alter table public.warnings enable row level security;
alter table public.follows enable row level security;

-- Walk policies
create policy "walks_select_own"
  on public.walks for select
  using (owner_id = auth.uid());

create policy "walks_insert_own"
  on public.walks for insert
  with check (owner_id = auth.uid());

-- Warnings policies: readable by all signed-in users, writable by reporter.
create policy "warnings_select_all_authed"
  on public.warnings for select
  using (auth.uid() is not null);

create policy "warnings_insert_own"
  on public.warnings for insert
  with check (reporter_id = auth.uid());

-- Follow policies
create policy "follows_select_own"
  on public.follows for select
  using (follower_id = auth.uid());

create policy "follows_insert_own"
  on public.follows for insert
  with check (follower_id = auth.uid());
